### PR TITLE
Typos and closes #13

### LINKED ISSUE #13: read through for potentially demotivating language
There are some scattered uses of phrases that are often demotivating. For example "simply", "basic".

Another example in [Episode 2](http://www.datacarpentry.org/python-socialsci/02-basics/) says:

>> The output is what you would probably have guessed at.

We want to avoid this type of language where possible. Other examples of demotivating language are discussed in [the instructor training curriculum](http://carpentries.github.io/instructor-training/03-expertise/#dismissive-language).

### PR DESCRIPTION
**Pull request by brownsarahm**
This corrects a number of typos throughout the whole lesson and removes a number of occurences of demotivating language.  It also changes the config file to use the DC logo instead of swc. 

This may not correct every occurrence of demotivating language, but I did find an replace on the word just and 'of course'

### CODE REVIEW

**Comment by sechilds** [comment]
Thanks for the fixes @brownsarahm 

I've gone through the changes and they look good. I am currently looking at the rendered output for each lesson. I will merge it once I finish that.

**Comment by sechilds** [comment]
I'm up to Episode 6 and I will continue reviewing this PR.

I did find one minor issue in Episode 5. In line 39, the spelling of Comma Separated Value is corrected but Separated is un-capitalized. If you could fix that and update the PR. Thanks again @brownsarahm for all the updates.

**Comment by brownsarahm** [comment]
done.

**Comment by sechilds** [comment]
Thanks @brownsarahm for the additional fixes. It is looking good.

One minor thing -- in episode 11, line 30 -- I think the title line is supposed to be: "Two datasets **containing** the same columns..."

Aside from that, I've gone through the changes and I'm good with merging it. Thanks for all the effort on this - it's a great contribution to the lesson.

**Comment by brownsarahm** [comment]
switched to containing. 
 and a bit more progress on the index page.

**Comment by ErinBecker** [comment]
Great teamwork! @sechilds - is this ready to merge?

**Comment by sechilds** [comment]
All the issues I found have been fixed. It is ready to be merged. 

I will do so now.

**Pull request merged**
