### PR TITLE
Plotting with Data: Update on #93.

### PR DESCRIPTION
**Pull request by vinisalazar**
This is an update on the work from #93.

I rebased the current `gh-pages` branch into the branch from that PR and fixed all conflicts.
I'm sure there are still things to be reviewed but I believe that this refreshes the status of the original PR.

Best,
V

### CODE REVIEW

**Comment by chendaniely** [comment]
From #93 this should also close #72

**Comment by chendaniely** [comment]
I didn't check the actual figures, but this PR updates the text and data examples from #93. so This can be merged in.

**Comment by chendaniely** [comment]
@brownsarahm and @katrinleinweber are you okay with the rebasing @vinisalazar did? I know both of you won't actually get the "commit" credit from this PR

**Comment by vinisalazar** [comment]
Thanks @chendaniely, I wasn't sure on the best way to merge the changes and so the commits were lost, sorry @brownsarahm and @katrinleinweber. If there's alternative that allows us to keep the original commits, I'd be happy to try it.

**Comment by brownsarahm** [comment]
no problem in losing my commits, there may also be more updates that I made in my fork, but I don't have time to finish fixing the PR.  https://github.com/brownsarahm/python-socialsci/tree/gh-pages

**Comment by vinisalazar** [comment]
Thanks @brownsarahm! I can have a look at your fork in the next few days and bring in the updates.

**Comment by katrinleinweber** [comment]
I'm fine with that as well, but you maybe mean @katrintirok ? She's in [#93's commits](https://github.com/datacarpentry/python-socialsci/pull/93/commits) ;-)

**Comment by katrintirok** [comment]
I am fine with it as well

**Comment by vinisalazar** [comment]
sorry for the wrong @ !

**Comment by vinisalazar** [comment]
Hi @annajiat @chendaniely,

do you reckon this PR is good for review and merge? I planned to continue working on this same branch.

Thanks!

**Comment by annajiat** [comment]
Closes #93

Looks good to me. Minor updates may be required, but we'll wait for the upcoming changes first. Thank you in advance.

Thank you @vinisalazar  @brownsarahm @chendaniely for the extensive contribution.

**Comment by annajiat** [comment]
Closes #72

**Pull request merged**
